# Python library for symbolic mathematics it gives function as sub symbols which make working with formulas ike 2x or sinx much more easier.
import sympy as sp

print("Enter the lower limits:")  # lower and upper limits asked by the user.
a = float(input())
print("Enter the upper limit")
b = float(input())
print("Enter the function:")  # Function entered by the user
x = sp.symbols('x')
function = input()
func = sp.sympify(function)
h = b-a  # h generated by h=upper-lower limit/n=1
print("The Ans Is\n")
first = h/2
# equation computated for the trapezoidal question
ans = first*(sp.N(func.subs(x, a))+sp.N(func.subs(x, b)))

print("The Ans is")
print("{:.5f}".format(ans))
